/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <BPM.h>
#include <Median.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_BPM_Should_Return_100PBM_From10msSamples(void);
extern void test_BPM_Should_Return_50PBM_From20msSamples(void);
extern void test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples(void);
extern void test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros(void);
extern void test_BPM_Should_Return_0_From0msSamples(void);
extern void test_BPM_Should_NotAlterPassedSamples(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples(void);
extern void test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test/TestBPM.c");
  RUN_TEST(test_BPM_Should_Return_100PBM_From10msSamples, 24);
  RUN_TEST(test_BPM_Should_Return_50PBM_From20msSamples, 32);
  RUN_TEST(test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples, 40);
  RUN_TEST(test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros, 48);
  RUN_TEST(test_BPM_Should_Return_0_From0msSamples, 56);
  RUN_TEST(test_BPM_Should_NotAlterPassedSamples, 64);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples, 77);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples, 88);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros, 99);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples, 110);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples, 121);
  RUN_TEST(test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples, 132);

  return (UnityEnd());
}
