/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <Median.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_5(void);
extern void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_0(void);
extern void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_10(void);
extern void test_Median_SortDesc_Should_Return_3_2_1_IfGiven_2_1_3(void);
extern void test_Median_SortDesc_Should_Return_5_4_IfGiven_4_5(void);
extern void test_Median_SortDesc_Should_Return_5_4_IfGiven_5_4(void);
extern void test_Median_SortDesc_Should_Return_7_6_3_2_IfGiven_2_7_3_6(void);
extern void test_Median_Should_Return_2_IfGiven_2_1_3(void);
extern void test_Median_Should_Return_5_IfGiven_4_5(void);
extern void test_Median_Should_Return_4_IfGiven_5_3(void);
extern void test_Median_Should_Return_3_IfGiven_2_7_3_6_1(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test/TestMedian.c");
  RUN_TEST(test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_5, 23);
  RUN_TEST(test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_0, 31);
  RUN_TEST(test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_10, 39);
  RUN_TEST(test_Median_SortDesc_Should_Return_3_2_1_IfGiven_2_1_3, 49);
  RUN_TEST(test_Median_SortDesc_Should_Return_5_4_IfGiven_4_5, 60);
  RUN_TEST(test_Median_SortDesc_Should_Return_5_4_IfGiven_5_4, 71);
  RUN_TEST(test_Median_SortDesc_Should_Return_7_6_3_2_IfGiven_2_7_3_6, 82);
  RUN_TEST(test_Median_Should_Return_2_IfGiven_2_1_3, 95);
  RUN_TEST(test_Median_Should_Return_5_IfGiven_4_5, 106);
  RUN_TEST(test_Median_Should_Return_4_IfGiven_5_3, 117);
  RUN_TEST(test_Median_Should_Return_3_IfGiven_2_7_3_6_1, 128);

  return (UnityEnd());
}
