Median_TestProject: Median.c File Reference
Median.c File Reference
#include <Median.h>
#include <stdlib.h>
Functions
void Median_SortDesc (int *Array, int Length)
int Median_int_CompDesc (const void *a, const void *b)
Sorting function requires sorted item comparator.
int Median (int *ArrayBuffer, int Length)
Function Documentation
int Median (int * ArrayBuffer, int Length)
Calculates a median from passed samples. Sorts passed samples, so the operation is destructive to the data!
Works with odd and even lengths of data. For even - averages two central data points
Parameters
ArrayBuffer Data samples to calculate median from. Buffer indicates that this should be a copy of the original data, cause passed array will be altered (sorted).
Length Data array length
Returns
Median value of the passed data
Definition at line 21 of file Median.c.
References Median_SortDesc().
Referenced by BPM_MedianFilter_Window3Samples().
int Median_int_CompDesc (const void * a, const void * b)
Sorting function requires sorted item comparator.
This function serves that purpose, it returns b - a value from items passed as pointers.
Parameters
a First compared param
b Second compared param
Returns
(b - a) calculated from pointed items value seen as int
See Also
Median_SortDesc
Definition at line 16 of file Median.c.
Referenced by Median_SortDesc().
void Median_SortDesc (int * Array, int Length)
Descending sort function. Implemented using qsort() included in stdlib.
Parameters
Array Array to be sorted
Length Sorted array length
Definition at line 11 of file Median.c.
References Median_int_CompDesc().
Referenced by Median().