Median_TestProject: /home/rrak/workspace/C_Median_TestProject/test/test_runners/TestMedian_Runner.c File Reference
TestMedian_Runner.c File Reference
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <Median.h>
Macros
#define RUN_TEST(TestFunc, TestLineNum)
Functions
void setUp (void)
void tearDown (void)
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_5 (void)
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_0 (void)
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_10 (void)
void test_Median_SortDesc_Should_Return_3_2_1_IfGiven_2_1_3 (void)
void test_Median_SortDesc_Should_Return_5_4_IfGiven_4_5 (void)
void test_Median_SortDesc_Should_Return_5_4_IfGiven_5_4 (void)
void test_Median_SortDesc_Should_Return_7_6_3_2_IfGiven_2_7_3_6 (void)
void test_Median_Should_Return_2_IfGiven_2_1_3 (void)
void test_Median_Should_Return_5_IfGiven_4_5 (void)
void test_Median_Should_Return_4_IfGiven_5_3 (void)
void test_Median_Should_Return_3_IfGiven_2_7_3_6_1 (void)
void resetTest (void)
int main (void)
Macro Definition Documentation
#define RUN_TEST (TestFunc, TestLineNum)
Value:
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}
Definition at line 4 of file TestMedian_Runner.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 53 of file TestMedian_Runner.c.
References RUN_TEST, test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_0(), test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_10(), test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_5(), test_Median_Should_Return_2_IfGiven_2_1_3(), test_Median_Should_Return_3_IfGiven_2_7_3_6_1(), test_Median_Should_Return_4_IfGiven_5_3(), test_Median_Should_Return_5_IfGiven_4_5(), test_Median_SortDesc_Should_Return_3_2_1_IfGiven_2_1_3(), test_Median_SortDesc_Should_Return_5_4_IfGiven_4_5(), test_Median_SortDesc_Should_Return_5_4_IfGiven_5_4(), and test_Median_SortDesc_Should_Return_7_6_3_2_IfGiven_2_7_3_6().
void resetTest (void)
Definition at line 45 of file TestMedian_Runner.c.
References setUp(), and tearDown().
void setUp (void)
Definition at line 12 of file TestBPM.c.
Referenced by resetTest().
void tearDown (void)
Definition at line 17 of file TestBPM.c.
Referenced by resetTest().
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_0 (void)
Definition at line 31 of file TestMedian.c.
References Median_int_CompDesc().
Referenced by main().
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_10 (void)
Definition at line 39 of file TestMedian.c.
References Median_int_CompDesc().
Referenced by main().
void test_Median_int_CompDesc_Should_ReturnDifference_b_minus_a_Given_b_7_And_a_5 (void)
Definition at line 23 of file TestMedian.c.
References Median_int_CompDesc().
Referenced by main().
void test_Median_Should_Return_2_IfGiven_2_1_3 (void)
Definition at line 95 of file TestMedian.c.
References Median().
Referenced by main().
void test_Median_Should_Return_3_IfGiven_2_7_3_6_1 (void)
Definition at line 128 of file TestMedian.c.
References Median().
Referenced by main().
void test_Median_Should_Return_4_IfGiven_5_3 (void)
Definition at line 117 of file TestMedian.c.
References Median().
Referenced by main().
void test_Median_Should_Return_5_IfGiven_4_5 (void)
Definition at line 106 of file TestMedian.c.
References Median().
Referenced by main().
void test_Median_SortDesc_Should_Return_3_2_1_IfGiven_2_1_3 (void)
Definition at line 49 of file TestMedian.c.
References Median_SortDesc().
Referenced by main().
void test_Median_SortDesc_Should_Return_5_4_IfGiven_4_5 (void)
Definition at line 60 of file TestMedian.c.
References Median_SortDesc().
Referenced by main().
void test_Median_SortDesc_Should_Return_5_4_IfGiven_5_4 (void)
Definition at line 71 of file TestMedian.c.
References Median_SortDesc().
Referenced by main().
void test_Median_SortDesc_Should_Return_7_6_3_2_IfGiven_2_7_3_6 (void)
Definition at line 82 of file TestMedian.c.
References Median_SortDesc().
Referenced by main().