Median_TestProject: /home/rrak/workspace/C_Median_TestProject/test/TestBPM.c File Reference
TestBPM.c File Reference
#include <BPM.h>
#include <Median.h>
#include <unity.h>
Functions
void setUp (void)
void tearDown (void)
void test_BPM_Should_Return_100PBM_From10msSamples (void)
void test_BPM_Should_Return_50PBM_From20msSamples (void)
void test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
void test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
void test_BPM_Should_Return_0_From0msSamples (void)
void test_BPM_Should_NotAlterPassedSamples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples (void)
Function Documentation
void setUp (void)
Definition at line 12 of file TestBPM.c.
void tearDown (void)
Definition at line 17 of file TestBPM.c.
void test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples (void)
Definition at line 132 of file TestBPM.c.
References BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
Definition at line 110 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
Definition at line 99 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
Definition at line 88 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples (void)
Definition at line 77 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
Definition at line 121 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_Should_NotAlterPassedSamples (void)
Definition at line 64 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_0_From0msSamples (void)
Definition at line 56 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From10msSamples (void)
Definition at line 24 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
Definition at line 48 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
Definition at line 40 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_50PBM_From20msSamples (void)
Definition at line 32 of file TestBPM.c.
References BPM().
Referenced by main().