Median_TestProject: /home/rrak/workspace/C_Median_TestProject/test/test_runners/TestBPM_Runner.c File Reference
TestBPM_Runner.c File Reference
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <BPM.h>
#include <Median.h>
Macros
#define RUN_TEST(TestFunc, TestLineNum)
Functions
void setUp (void)
void tearDown (void)
void test_BPM_Should_Return_100PBM_From10msSamples (void)
void test_BPM_Should_Return_50PBM_From20msSamples (void)
void test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
void test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
void test_BPM_Should_Return_0_From0msSamples (void)
void test_BPM_Should_NotAlterPassedSamples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
void test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples (void)
void resetTest (void)
int main (void)
Macro Definition Documentation
#define RUN_TEST (TestFunc, TestLineNum)
Value:
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}
Definition at line 4 of file TestBPM_Runner.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 55 of file TestBPM_Runner.c.
References RUN_TEST, test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples(), test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples(), test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros(), test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples(), test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples(), test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples(), test_BPM_Should_NotAlterPassedSamples(), test_BPM_Should_Return_0_From0msSamples(), test_BPM_Should_Return_100PBM_From10msSamples(), test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros(), test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples(), and test_BPM_Should_Return_50PBM_From20msSamples().
void resetTest (void)
Definition at line 47 of file TestBPM_Runner.c.
References setUp(), and tearDown().
void setUp (void)
Definition at line 12 of file TestBPM.c.
Referenced by resetTest().
void tearDown (void)
Definition at line 17 of file TestBPM.c.
Referenced by resetTest().
void test_BPM_MedianFilter_Window3Samples_Should_NotAlterPassedSamples (void)
Definition at line 132 of file TestBPM.c.
References BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From10msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
Definition at line 110 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
Definition at line 99 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
Definition at line 88 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamples (void)
Definition at line 77 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_MedianFilter_Window3Samples_Should_Return_50PBM_From20msSamplesWithIsolated_1ms_AND_100ms_Samples (void)
Definition at line 121 of file TestBPM.c.
References BPM(), and BPM_MedianFilter_Window3Samples().
Referenced by main().
void test_BPM_Should_NotAlterPassedSamples (void)
Definition at line 64 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_0_From0msSamples (void)
Definition at line 56 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From10msSamples (void)
Definition at line 24 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From_10ms_10ms_0ms_0ms_SamplesIgnoringZeros (void)
Definition at line 48 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_100PBM_From_15ms_10ms_5ms_Samples (void)
Definition at line 40 of file TestBPM.c.
References BPM().
Referenced by main().
void test_BPM_Should_Return_50PBM_From20msSamples (void)
Definition at line 32 of file TestBPM.c.
References BPM().
Referenced by main().