Median_TestProject: /home/rrak/workspace/C_Median_TestProject/test/test_runners/TestProductionCode_Runner.c File Reference
TestProductionCode_Runner.c File Reference
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <Median.h>
#include <BPM.h>
Macros
#define RUN_TEST(TestFunc, TestLineNum)
Functions
void setUp (void)
void tearDown (void)
void test_OneFunc_Should_AllwaysReturnOne (void)
void resetTest (void)
int main (void)
Macro Definition Documentation
#define RUN_TEST (TestFunc, TestLineNum)
Value:
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}
Definition at line 4 of file TestProductionCode_Runner.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 46 of file TestProductionCode_Runner.c.
References RUN_TEST, and test_OneFunc_Should_AllwaysReturnOne().
void resetTest (void)
Definition at line 38 of file TestProductionCode_Runner.c.
References setUp(), and tearDown().
void setUp (void)
Definition at line 12 of file TestBPM.c.
Referenced by resetTest().
void tearDown (void)
Definition at line 17 of file TestBPM.c.
Referenced by resetTest().
void test_OneFunc_Should_AllwaysReturnOne (void)
Referenced by main().